version: '3'

services:
    epgstation:
        build:
            context: epgstation
        volumes:
            - ../:/work
            - .vscode-server:/home/node/.vscode-server
        ports:
          - 8888:8888
          - 8889:8889
        command: sleep infinity
